# -*- coding: utf-8 -*- 
'''
Created on 2014-2-12

@author: GroundMelon
'''

DISPLAY_UAVINFO = 0
DISPLAY_VIDEO = 1
DISPLAY_INDEPENDENT_VIDEO = 2
DISPLAY_TRACK_VIDEO = 3
UPDATE_INFORMATION = 4
RECORD_VIDEO = 5
TRACK_OBJECT = 6
DISPLAY_XBEE_DATA = 7
USING_JOYSTICK = 8


DISPLAY_TRACK_STATE_RAW = 1
DISPLAY_TRACK_STATE_SELECTION = 2
DISPLAY_TRACK_STATE_RESULT = 3

DEFINITION_LOCALS_DICT = locals().copy()